### ISSUE TITLE
NSolid 1.3

### ISSUE THREAD

**Issue by johanneswuerbach** [nodesource/docker-nsolid#6]
Hello,

looks like NSolid 1.3 has been released. Will the docker images be also updated soon? 

https://nodesource.com/blog/nsolid-v1-3/

Thanks 🙇

**Comment by retrohacker** [comment]
Hey @johanneswuerbach!

They should be available on the Docker Hub now.

The build time on our docker images is still pretty high due to the  tests we run. This release of images took several iterations to get out the door.

These should be released in closer lockstep with the upstream project moving forward.

Build logs of the last two builds are available in this project repo if that helps!
